version: '3.8'

services:
  client:
    container_name: legendcity_frontend
    command: npm run start
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src/
