name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
    build:
      runs-on: ubuntu-20.04
      steps:

        - name: Checkout master
          uses: actions/checkout@v2

        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}

        - name: install dependencies
          run: npm install

        - name: run the tests
          run: npm test

        - name: run linting
          run: npm test

        - name: build
          run: npm run build